### ISSUE TITLE
Errors in CNN.py

### ISSUE THREAD

**Issue by ozgemercanoglu** [Adopteruf/Action_Recognition_using_Visual_Attention#5]
I am trying to execute your codes.  I am working with Windows10 and anaconda. Tensorflow for Windows does not supported with Python 2.7. Therefore, I am working with Python3.5. My detailed packages is attached. I run pre-data.py by changing some parts of the code. However, when I run CNN.py, I get some errors:

Traceback (most recent call last):
  File "CNN.py", line 108, in <module>
    main()
  File "CNN.py", line 30, in main
    vggnet.build()
  File "C:\Users\ASUS\Desktop\TF3.5_attention\core\vggnet.py", line 58, in build
    self.build_params()
  File "C:\Users\ASUS\Desktop\TF3.5_attention\core\vggnet.py", line 19, in build_params
    model = scipy.io.loadmat(self.vgg_path)
  File "C:\Users\ASUS\Anaconda3\envs\tensorflow3.5\lib\site-packages\scipy\io\matlab\mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Users\ASUS\Anaconda3\envs\tensorflow3.5\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "C:\Users\ASUS\Anaconda3\envs\tensorflow3.5\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 723, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 969, in scipy.io.matlab.mio5_utils.VarReader5.read_struct
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 705, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 778, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 195, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 171, in scipy.io.matlab.streams.ZlibInputStream.read_into
  File "streams.pyx", line 158, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -3 while decompressing data: incorrect data check

Do you have any idea what the cause of the error is?

![packages](https://user-images.githubusercontent.com/14040021/44972641-9702d080-af62-11e8-82f6-e9427ea5d568.PNG)

**Comment by 13293824182** [comment]
hi，Did you finally run this code successfully? I want to talk about the environment of the code running, my WeChat is 17801165363.

**Comment by ozgemercanoglu** [comment]
Unfortunately, I could not @13293824182
